Models/CompanySummary.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ThreePage.Models
{
    public class CompanySummary
    {
        public int EmployeeCount { get; set; }
        public int AverageDepartmentEmployeeCount { get; set; }
    }
}

Models/Department.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ThreePage.Models
{
    public class Department
    {
        public int Id { get; set; }

        [Display(Name = "部门名称")]
        public string Name { get; set; }
        public string Location { get; set; }
        public int EmployeeCount { get; set; }
    }
}

Models/Employee.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Three.Models
{
    public class Employee
    {
        public int Id { get; set; }
        public int DepartmentId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Gender Gender { get; set; }
        public bool Fired { get; set; }
    }
    public enum Gender
    {
        女 = 0,
        男 = 1
    }
}

Pages/Department/AddDepartment.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ThreePage.Services;

namespace ThreePage.Pages.Department
{
    public class AddDepartmentModel : PageModel
    {
        private readonly IDepartmentService _departmentService;

        [BindProperty]
        public Models.Department Department { get; set; }
        public void OnGet()
        {
        }

        public AddDepartmentModel(IDepartmentService departmentService)
        {
            _departmentService = departmentService;
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();            
            }
            await _departmentService.Add(Department);
            return RedirectToPage("/Index");
        }
    }
}

Pages/Employee/AddEmployee.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ThreePage.Services;

namespace ThreePage.Pages.Employee
{
    public class AddEmployeeModel : PageModel
    {
        private readonly IEmployeeService _employeeService;

        public AddEmployeeModel(IEmployeeService employeeService)
        {
            _employeeService = employeeService;
        }
        [BindProperty]
        public Three.Models.Employee Employee { get; set; }

        public async Task<IActionResult> OnPostAsync(int departmentId)
        {
            Employee.DepartmentId = departmentId;

            if (!ModelState.IsValid)
            {
                return Page();
            }
            await _employeeService.Add(Employee);
            return RedirectToPage("EmployeeList", new { departmentId });
        }
    }
}

Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace ThreePage.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ThreePage.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ThreePage.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

ViewComponents/CompanySummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ThreePage.Services;

namespace ThreePage.ViewComponents
{
    public class CompanySummaryViewComponent : ViewComponent
    {
        private readonly IDepartmentService _departmentService;

        public CompanySummaryViewComponent(IDepartmentService departmentService)
        {
            _departmentService = departmentService;
        }
        public async Task<IViewComponentResult> InvokeAsync(string title)
        {
            ViewBag.Title = title;
            var summary = await _departmentService.GetCompanySummary();
            return View(summary);
        }
    }
}

Pages/Components/CompanySummary/Default.cshtml
@model ThreePage.Models.CompanySummary

<div class="small">
    <div class="row h3">@ViewBag.Title</div>
    <div class="row">
        <div class="col-md-8">员工总数：</div>
        <div class="col-md-4">@Model.EmployeeCount</div>
    </div>
    <div class="row">
        <div class="col-md-8">部门平均人数：</div>
        <div class="col-md-4">@Model.AverageDepartmentEmployeeCount</div>
    </div>
</div>  

Pages/Department/AddDepartment.cshtml
@page
@model ThreePage.Pages.Department.AddDepartmentModel
<form asp-action="Add" method="post">
    <div class="row form-group">
        <div class="col-md-2 offset-md-2">
            <label asp-for="Department.Name"></label>
        </div>
        <div class="col-md-6">
            <input class="form-control" asp-for="Department.Name" />
        </div>
    </div>
    <div class="row form-group">
        <div class="col-md-2 offset-md-2">
            <label asp-for="Department.Location"></label>
        </div>
        <div class="col-md-6">
            <input class="form-control" asp-for="Department.Location" />
        </div>
    </div>
    <div class="row form-group">
        <div class="col-md-2 offset-md-2">
            <label asp-for="Department.EmployeeCount"></label>
        </div>
        <div class="col-md-6">
            <input class="form-control" asp-for="Department.EmployeeCount" />
        </div>
    </div>
    <div class="row">
        <div class="col-md-2 offset-md-2">
            <button type="submit" class="btn btn-primary">Add</button>
        </div>
    </div>
</form>

Pages/DisplayTemplates/Department.cshtml
@model ThreePage.Models.Department
<tr>
    <td>@Model.Name</td>
    <td>@Model.Location</td>
    <td>@Model.EmployeeCount</td>
    <td>
        <a asp-page="Employee/EmployeeList" asp-route-departmentId="@Model.Id">Employees</a>
    </td>
</tr>

Pages/DisplayTemplates/Employee.cshtml
@using Three.Models
@model Employee
<tr>
    <td>@Model.FirstName</td>
    <td>@Model.LastName</td>
    <td>@Model.Gender</td>
    <td>@(Model.Fired?"是":"")</td>
    <td>
        @if (!Model.Fired)
        {
            @*<a asp-action="Fire" asp-route-employeeId="@Model.Id">
                    Fire
                </a>*@
            <a asp-page="EmployeeList" asp-page-handler="Fire" asp-route-employeeId="@Model.Id" asp-route-departmentId="@Model.DepartmentId">Fire</a>
        }
    </td>
</tr>

Pages/Employee/AddEmployee.cshtml
@page "{departmentId:int}"
@using Three.Models
@model ThreePage.Pages.Employee.AddEmployeeModel
<form method="post">

    <div class="row form-group">
        <div class="col-md-2 offset-md-2">
            <label asp-for="Employee.FirstName"></label>
        </div>
        <div class="col-md-6">
            <input class="form-control" asp-for="Employee.FirstName" />
        </div>
    </div>
    <div class="row form-group">
        <div class="col-md-2 offset-md-2">
            <label asp-for="Employee.LastName"></label>
        </div>
        <div class="col-md-6">
            <input class="form-control" asp-for="Employee.LastName" />
        </div>
    </div>
    <div class="row form-group">
        <div class="col-md-2 offset-md-2">
            <label asp-for="Employee.Gender"></label>
        </div>
        <div class="col-md-6">
            <select class="form-control" asp-for="Employee.Gender" asp-items="Html.GetEnumSelectList<Gender>()">
            </select>
            @*<input class="form-control" asp-for="Gender" />*@
        </div>
    </div>
    <div class="row">
        <div class="col-md-2 offset-md-2">
            <button type="submit" class="btn btn-primary">Add</button>
        </div>
    </div>
</form>

Pages/Employee/EmployeeList.cshtml
@page "{departmentId:int}"
@using Microsoft.AspNetCore.Mvc.RazorPages
@using ThreePage.Services
@using ThreePage.Models
@model EmployeeListModel
<div class="row">
    <div class="col-md-10 offset-md-2">
        <table class="table">
            <tr>
                <th>
                    First Name
                </th>
                <th>
                    Last Name
                </th>
                <th>
                    Gender
                </th>
                <th>
                    Is Fired
                </th>
                <th>
                    操作
                </th>
            </tr>
            @Html.DisplayFor(x => x.Employees)
        </table>
        <a asp-page="AddEmployee" asp-route-departmentId="@ViewData["DepartmentId"]">Add</a>
    </div>
</div>
@*<div class="row">
        <div class="col-md-4 offset-md-2">
            <a asp-action="Add" asp-route-departmentId="@ViewBag.DepartmentId">Add</a>
        </div>
    </div>*@

@functions{
    public class EmployeeListModel : PageModel
    {
        public readonly IEmployeeService _employeeService;

        public EmployeeListModel(IEmployeeService employeeService)
        {
            _employeeService = employeeService;
        }
        public IEnumerable<Three.Models.Employee> Employees { get; set; }

        public async Task OnGet(int departmentId)
        {
            Employees = await _employeeService.GetByDepartmentId(departmentId);
            ViewData["DepartmentId"] = departmentId;
        }
        public async Task<IActionResult> OnGetFireAsync(int employeeId, int departmentId)
        {
            await _employeeService.Fire(employeeId);

            return RedirectToPage("EmployeeList", new { departmentId });
        }
    }
}

Pages/Index.cshtml
@page
@using ThreePage.Services
@inject IDepartmentService departmentService
<div class="row">
    <div class="col-md-10 offset-md-2">
        <table class="table">
            <tr>
                <th>
                    Name
                </th>
                <th>
                    Location
                </th>
                <th>
                    Employee Count
                </th>
                <th>
                    操作
                </th>
            </tr>
            @Html.DisplayFor(x => x.Departments)
        </table>
    </div>
</div>
<div class="row">
    <div class="col-md-4">
        <a asp-page="Department/AddDepartment">Add</a>
    </div>
    <div class="col-md-4">
        @await Component.InvokeAsync("CompanySummary",new { title = "部门列表页的汇总"})
        <vc:company-summary title="部门列表页的汇总2"></vc:company-summary>
    </div>
</div>
@functions{
    public IEnumerable<ThreePage.Models.Department> Departments { get; set; }

    public async Task OnGetAsync()
    {

        Departments = await departmentService.GetAll();

    }
}

Pages/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <environment include="Development">
        <link rel="stylesheet" asp-href-include="css/*" asp-href-exclude="css/all.min.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" asp-href-include="css/all.min.css" />
    </environment>
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-md-2">
                <img asp-append-version="true" alt="Logo" src="~/images/logo.png" style="height:60px" />
            </div>
            <div class="col-md-10">
                <span class="h2">@ViewBag.Title</span>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                @RenderBody()
            </div>
        </div>
    </div>

</body>
</html>